name: Publish

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      release:
        description: 'Release number'
        required: true

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Build
      run: make

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: kubenv-*-amd64
        asset_name: kubenv
        tag: ${{ github.event.inputs.release || github.ref }}
        file_glob: true
        overwrite: true
