name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: make build

    - name: Publish test
      run: make publish_test
      env:
        TAG_REF: ${{ github.ref }}

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: kubenv-*-amd64
        asset_name: kubenv
        tag: ${{ github.ref }}
        file_glob: true
        overwrite: true
